### PR TITLE
Test hook_civicrm_postCommit

### PR DESCRIPTION
**Pull request by semseysandor**
simulate a logged-in and a not logged-in user

### CODE REVIEW

**Comment by semseysandor** [comment]
This PR fails, because:
```
CRM_ Auto Parent Tag_ Hook
 ✘ Post commit hook with logged in user [267.32 ms]
   │
   │ Failure in api call for UFMatch get:  Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop'
   │ #0 [internal function]: PHPUnit\Util\ErrorHandler->__invoke(2, 'Function must b...', '/var/www/html/c...', 76, Array)
   │ #1 /var/www/html/composer-site.com/vendor/civicrm/civicrm-core/Civi/API/Subscriber/DebugSubscriber.php(76): xdebug_time_index()
```

With XDebug 3 it is not possible to change `xdebug.mode` runtime, it is set before the request. This function is not enabled (it is called in: `ContactTestTrait::createLoggedInUser()` to simulate a logged-in user.

Possible solutions:
- set XDEBUG_MODE=develop in `main.yml`: this way we lose the coverage report
- revert to XDebug 2
- wait until XDebug 3 is supported in `civicrm-core`

**Comment by semseysandor** [comment]
I went with settting XDEBUG_MODE=develop in main.yml

This way we lose coverage report, but this PR can get merged, alos we can simulate logged in user in tests

**Comment by akosgarai** [comment]
I don't like this solution due to the missing coverage report. Isn't it possible to mock the logged in user without the trait? Or other option isn't it possible to implement the same logic in the postProcess hook? In this case you don't need to take care about the logged in user, because you can expect that the CRM handled it well. You only need to provide a form and pass it to the postProcess handler function and then do the same api calls to check the results. Or is there a specific reason that excludes the postProcess hook?

**Comment by semseysandor** [comment]
I implemented the `createLoggedInUser()` method without the traits. Now it works with `xdebug_mode=coverage`, and it could be used in other extensions if needed.

**Review by akosgarai — APPROVED** [review]
The coverage report is back :+1:

**Pull request merged**
